# Dialyzer warning filters (Dialyxir `{file, warning_type}` tuples).
# Regenerate candidates: `mix dialyzer --format ignore_file --ignore-exit-status`
# then shrink this list as specs/contracts are tightened. Added 2026-04-21.
[
  {"lib/kiln/agents/role.ex", :pattern_match},
  {"lib/kiln/agents/role.ex", :pattern_match_cov},
  {"lib/kiln/artifacts.ex", :invalid_contract},
  {"lib/kiln/artifacts.ex", :no_return},
  {"lib/kiln/artifacts.ex", :call},
  {"lib/kiln/artifacts/artifact.ex", :contract_supertype},
  {"lib/kiln/blockers.ex", :no_return},
  {"lib/kiln/blockers/reason.ex", :contract_supertype},
  {"lib/kiln/diagnostics/snapshot.ex", :pattern_match},
  {"lib/kiln/git.ex", :contract_supertype},
  {"lib/kiln/github.ex", :contract_supertype},
  {"lib/kiln/github/cli.ex", :contract_supertype},
  {"lib/kiln/github/dogfood.ex", :contract_with_opaque},
  {"lib/kiln/model_registry.ex", :contract_supertype},
  {"lib/kiln/notifications.ex", :contract_supertype},
  {"lib/kiln/notifications/dedup_cache.ex", :contract_supertype},
  {"lib/kiln/policies.ex", :extra_range},
  {"lib/kiln/policies.ex", :missing_range},
  {"lib/kiln/policies/failure_class.ex", :contract_supertype},
  {"lib/kiln/runs/run.ex", :contract_supertype},
  {"lib/kiln/runs/transitions.ex", :contract_supertype},
  {"lib/kiln/sandboxes/harvester.ex", :no_return},
  {"lib/kiln/sandboxes/harvester.ex", :call},
  {"lib/kiln/sandboxes/harvester.ex", :unused_fun},
  {"lib/kiln/sandboxes/hydrator.ex", :pattern_match},
  {"lib/kiln/sandboxes/hydrator.ex", :unused_fun},
  {"lib/kiln/specs/scenario_compiler.ex", :extra_range},
  {"lib/kiln/specs/scenario_parser.ex", :pattern_match_cov},
  {"lib/kiln/stages/contract_registry.ex", :contract_supertype},
  {"lib/kiln/stages/stage_run.ex", :contract_supertype},
  {"lib/kiln/work_units/jsonl_adapter.ex", :extra_range},
  {"lib/kiln/work_units/pubsub.ex", :contract_supertype},
  {"lib/kiln/work_units/work_unit.ex", :contract_supertype},
  {"lib/kiln/work_units/work_unit_event.ex", :contract_supertype},
  {"lib/kiln/workflows.ex", :pattern_match_cov},
  {"lib/kiln/workflows/schema_registry.ex", :contract_supertype}
]
