defmodule Kiln.Specs.ScenarioCompiler do
  @moduledoc """
  Compiles validated scenario IR into deterministic ExUnit modules under
  `test/generated/kiln_scenarios/<revision_id>/` (SPEC-02).

  Codegen is template-only: scenario metadata is emitted as comments and
  string literals via `inspect/1`. **Assert** steps map `expect` to
  `assert true` / `assert false` only. **Shell** steps emit argv-only
  `System.cmd/3` calls (no shell string).
  """

  alias Kiln.Specs.SpecRevision

  @doc """
  Canonical sha256 (lowercase hex) over sorted scenario ids concatenated with
  canonical JSON for the merged IR map (sorted keys, sorted scenario ids).
  """
  @spec manifest_sha256(map()) :: String.t()
  def manifest_sha256(%{"scenarios" => scenarios} = ir) when is_list(scenarios) do
    normalized = normalize_ir_for_digest(ir)
    payload = Jason.encode!(normalized)
    :crypto.hash(:sha256, payload) |> Base.encode16(case: :lower)
  end

  defp normalize_ir_for_digest(%{"scenarios" => scenarios}) do
    sorted =
      scenarios
      |> Enum.sort_by(fn s -> Map.get(s, "id") || Map.get(s, :id) end)

    %{"scenarios" => sorted}
  end

  @doc """
  Writes `*_test.exs` for the revision and returns `{:ok, rel_path}` relative
  to the project root.
  """
  @spec compile(SpecRevision.t(), map()) :: {:ok, String.t()} | {:error, term()}
  def compile(%SpecRevision{} = rev, ir) do
    uuid = revision_uuid_string_for_path!(rev.id)
    base = Path.join(["test", "generated", "kiln_scenarios", uuid])
    File.mkdir_p!(base)

    mod = module_name(rev)
    rel = Path.join(base, "scenarios_test.exs")
    abs = Path.join(Mix.Project.project_file() |> Path.dirname(), rel)

    content = render_module(mod, ir, uuid)
    File.write!(abs, content)
    {:ok, rel}
  end

  defp module_name(%SpecRevision{id: id}) do
    hex =
      id
      |> Ecto.UUID.cast!()
      |> String.replace("-", "")
      |> String.downcase()

    "Kiln.GeneratedScenarios.R#{hex}"
  end

  defp revision_uuid_string_for_path!(id) do
    case Ecto.UUID.cast(id) do
      {:ok, u} -> u
      :error -> raise ArgumentError, "invalid revision id: #{inspect(id)}"
    end
  end

  defp render_module(mod, %{"scenarios" => scenarios}, revision_uuid) do
    tests = Enum.map_join(scenarios, "\n\n", &render_scenario_test/1)

    """
    # generated by Kiln.Specs.ScenarioCompiler — do not edit by hand
    # revision_id: #{revision_uuid}
    defmodule #{mod} do
      use ExUnit.Case

      @moduletag :kiln_scenario

    #{tests}
    end
    """
  end

  defp render_scenario_test(scenario) do
    id = Map.get(scenario, "id") || Map.get(scenario, :id)
    desc = Map.get(scenario, "description") || Map.get(scenario, :description) || ""
    steps = Map.get(scenario, "steps") || Map.get(scenario, :steps) || []

    body = Enum.map_join(steps, "\n", &render_step/1)

    """
      test #{inspect("scenario: #{id}")} do
        # #{inspect(desc)}
    #{body}
      end
    """
  end

  defp render_step(step) do
    case Map.get(step, "kind") || Map.get(step, :kind) do
      "assert" -> render_assert_step(step)
      "shell" -> render_shell_step(step)
      kind -> "    flunk(\"unsupported scenario step kind: #{inspect(kind)}\")"
    end
  end

  defp render_assert_step(step) do
    expect = Map.get(step, "expect") || Map.get(step, :expect)

    case expect do
      "false" -> "    assert false"
      _ -> "    assert true"
    end
  end

  defp render_shell_step(step) do
    argv = Map.get(step, "argv") || Map.get(step, :argv) || []
    cwd = Map.get(step, "cwd") || Map.get(step, :cwd)
    argv_literal = inspect(Enum.map(argv, &to_string/1))

    with_cd =
      case cwd do
        c when is_binary(c) and c != "" ->
          [
            "    opts = [stderr_to_stdout: true]",
            "    opts = Keyword.put(opts, :cd, Path.expand(#{inspect(c)}, File.cwd!()))"
          ]

        _ ->
          ["    opts = [stderr_to_stdout: true]"]
      end

    [
      "    argv = #{argv_literal}",
      "    [program | args] = argv"
    ]
    |> Kernel.++(with_cd)
    |> Kernel.++([
      "    {output, exit_code} = System.cmd(program, args, opts)",
      "    assert exit_code == 0, output"
    ])
    |> Enum.join("\n")
  end
end
