defmodule Mix.Tasks.Kiln.Sandbox.Build do
  use Mix.Task

  @shortdoc "Build the Kiln sandbox Docker image and update images.lock"

  @images_lock "priv/sandbox/images.lock"
  @dockerfile "priv/sandbox/elixir.Dockerfile"
  @base_image "hexpm/elixir:1.19.5-erlang-28.1.1-alpine-3.21"

  @impl Mix.Task
  def run(_args) do
    image_tag = "kiln/sandbox-elixir:#{git_sha()}"

    {_out, status} =
      System.cmd("docker", ["build", "-f", @dockerfile, "-t", image_tag, "."],
        into: IO.stream(:stdio, :line)
      )

    if status != 0 do
      Mix.raise("docker build failed (exit #{status})")
    end

    {digest_out, 0} =
      System.cmd("docker", ["inspect", "--format={{index .RepoDigests 0}}", image_tag])

    digest =
      digest_out
      |> String.trim()
      |> String.split("@")
      |> List.last()

    lock_contents = """
    # Auto-generated by `mix kiln.sandbox.build`. Commit to track image evolution.
    elixir:
      image_ref: "#{image_tag}"
      image_digest: "#{digest}"
      built_at: "#{DateTime.utc_now() |> DateTime.truncate(:second) |> DateTime.to_iso8601()}"
      base_image: "#{@base_image}"
    """

    File.write!(@images_lock, lock_contents)
    Mix.shell().info("Built #{image_tag}\nDigest: #{digest}\nWrote #{@images_lock}")
  end

  defp git_sha do
    case System.cmd("git", ["rev-parse", "--short", "HEAD"]) do
      {sha, 0} -> String.trim(sha)
      _ -> "unknown"
    end
  end
end
