import Config

# Configure your database.
#
# Credentials match `compose.yaml` (`POSTGRES_USER=kiln` /
# `POSTGRES_PASSWORD=kiln_dev`). When `KILN_DB_ROLE` is set in the
# environment, `config/runtime.exs` issues `SET ROLE <role>` after
# connect — the migration runbook is
# `KILN_DB_ROLE=kiln_owner mix ecto.migrate` (DDL as owner), and the
# default runtime session runs as kiln_app (D-48).
config :kiln, Kiln.Repo,
  username: "kiln",
  password: "kiln_dev",
  hostname: "localhost",
  database: "kiln_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  # pool_size: 20 — D-68 budget (matches :prod default in config/runtime.exs).
  # See lib/kiln/boot_checks.ex check_oban_queue_budget!/0 for the paired
  # aggregate-16 Oban invariant.
  pool_size: 20

# SPEC-04: narrow role for holdout reads (same host/DB as `Kiln.Repo`).
config :kiln, Kiln.Repo.VerifierReadRepo,
  username: "kiln_verifier",
  password: "kiln_dev_verifier",
  hostname: "localhost",
  database: "kiln_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 2

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :kiln, KilnWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # `KILN_DEV_BIND_ALL=1` is handled in `config/runtime.exs` (T-02: no env
  # reads in compile-time config files). Published-port bind uses
  # `ip: {0, 0, 0, 0}` — see README “Optional: Dev Container”.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "N69Pe5/Fib3NPj/cVBZVfp2aWVyqLdfpkyN0sbaTNsVxMPu+D1b6fp+RxA4tKEpT",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:kiln, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:kiln, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :kiln, KilnWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/kiln_web/router\.ex$"E,
      ~r"lib/kiln_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :kiln, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Phase 999.2: local-first default — operator chrome shows Demo.
config :kiln, :operator_runtime_mode, :demo

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Sigra email delivery (dev) — adapter is set on the raw Swoosh.Mailer
# module, not the Sigra.Mailer behaviour wrapper.
config :kiln, Kiln.Mailer, adapter: Swoosh.Adapters.Local

config :swoosh, :api_client, false
